### ISSUE TITLE
Foreign key 'ON' clause causes error

### ISSUE THREAD

**Issue by martintreurnicht** [bgranvea/mysql2h2-converter#2]
If you have a clause like `CONSTRAINT `user_email_user_id_key` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE` it causes the following error:

```
java.lang.IllegalArgumentException: Cannot parse next statement
    at com.granveaud.mysql2h2converter.parser.SQLParserManager$ScriptIterator.parseNextStatement(SQLParserManager.java:25)
    at com.granveaud.mysql2h2converter.parser.SQLParserManager$ScriptIterator.next(SQLParserManager.java:37)
    at com.granveaud.mysql2h2converter.parser.SQLParserManager$ScriptIterator.next(SQLParserManager.java:12)
    at com.granveaud.mysql2h2converter.converter.H2Converter$ConverterIterator.loadNextStatements(H2Converter.java:28)
    at com.granveaud.mysql2h2converter.converter.H2Converter$ConverterIterator.<init>(H2Converter.java:23)
    at com.granveaud.mysql2h2converter.converter.H2Converter.convertScript(H2Converter.java:221)
    at com.granveaud.mysql2h2converter.converter.ConverterTest.executeScript(ConverterTest.java:86)
    at com.granveaud.mysql2h2converter.converter.ConverterTest.loadScript(ConverterTest.java:148)
    at com.granveaud.mysql2h2converter.converter.ConverterTest.testScript6(ConverterTest.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: com.granveaud.mysql2h2converter.parser.ParseException: Encountered " "ON" "ON "" at line 17, column 108.
Was expecting one of:
    ")" ...
    "," ...

    at com.granveaud.mysql2h2converter.parser.SQLParser.generateParseException(SQLParser.java:3161)
    at com.granveaud.mysql2h2converter.parser.SQLParser.jj_consume_token(SQLParser.java:3037)
    at com.granveaud.mysql2h2converter.parser.SQLParser.CreateTableDefinition(SQLParser.java:579)
    at com.granveaud.mysql2h2converter.parser.SQLParser.CreateTableStatement(SQLParser.java:421)
    at com.granveaud.mysql2h2converter.parser.SQLParser.CreateStatement(SQLParser.java:359)
    at com.granveaud.mysql2h2converter.parser.SQLParser.Statement(SQLParser.java:103)
    at com.granveaud.mysql2h2converter.parser.SQLParser.ScriptStatement(SQLParser.java:76)
    at com.granveaud.mysql2h2converter.parser.SQLParserManager$ScriptIterator.parseNextStatement(SQLParserManager.java:23)
    ... 37 more

```

**Comment by roytruelove** [comment]
+1
